### ISSUE TITLE
Fatal Python error: Aborted when use library svox

### ISSUE THREAD

**Issue by katealenic** [sxyu/plenoctree#1]
Hi, when i run python -m octree.task_manager octree/config/tt_sh25.json --gpus="0"
![image](https://user-images.githubusercontent.com/24976188/116885563-af09e100-ac30-11eb-99ec-10dfa65a9260.png)
This error rise in line 205
![image](https://user-images.githubusercontent.com/24976188/116885747-e8425100-ac30-11eb-8afe-31f783b78483.png)
But this library PyTorch CUDA Extension of PlenOctrees and installed by git url.
How can I solve this problem?

**Comment by liruilong940607** [comment]
I believe your svox is not properly built. Did you installed using `conda create -f environments.yml` ? And what's your pytorch version (`python -c "import torch; print(torch.version.cuda)"`) as well as nvcc version (`nvcc --version`)?

**Comment by sxyu** [comment]
please provide your GPU model as well

**Comment by katealenic** [comment]
And after reinstall svox i have this error
![image](https://user-images.githubusercontent.com/24976188/117855249-f75d7a80-b292-11eb-8fc6-481174f41504.png)

**Comment by katealenic** [comment]
I reinstall torch, but i have this error when I use pip install git+https://github.com/sxyu/svox.git

![image](https://user-images.githubusercontent.com/24976188/117934139-0253f180-b30b-11eb-9f86-b57e9f20210f.png)

**Comment by katealenic** [comment]
I solve this problem when reinstall torch for version nvcc. Thank you!
