### ISSUE TITLE
Training problem

### ISSUE THREAD

**Issue by SSground** [sxyu/plenoctree#2]
When I Training and evaluation on TanksAndTemple dataset.
`python -m nerf_sh.train  --train_dir $CKPT_ROOT/$SCENE/ --config$CONFIG_FILE  --data_dir $DATA_ROOT/$SCENE/`
（NO Install GPU and TPU support for Jax.）
There are the following errors
![bddb316a42cc6668d2bb1fed23a97f6](https://user-images.githubusercontent.com/27821863/118628434-2d54ae80-b7ff-11eb-908b-e03c9f93ea81.jpg)
![7633f460bbda3cd6f3040d11fae3c34](https://user-images.githubusercontent.com/27821863/118628449-304f9f00-b7ff-11eb-8547-47609b79f99f.jpg)

**Comment by SSground** [comment]
supplement
![08becd271babcb6b9b48f82e62e0e06](https://user-images.githubusercontent.com/27821863/118630584-3b0b3380-b801-11eb-9659-efd87ba400ac.jpg)

**Comment by huying163** [comment]
单独运行显示一个npz文件的代码已经能够顺利跑通了，但是如果要用我们自己的原始图片数据集，需要用他提供的一份转换代码，将原始的图片数据集转换成它代码里需要的npz格式，但是这个转换代码没有什么详细的说明，而且没有给出图像数据集应该具有的格式。然后这个报错是在运行转换代码的时候报的，应该是提示数据集格式有问题，缺少了一些关键的文件，但是我不是很清楚这个CamPose.inf是什么[捂脸]

**Comment by StevenLzq** [comment]
你安装jax for cuda的时候有没有遇到jax has no module api这个问题

**Comment by SSground** [comment]
> When I Training and evaluation on TanksAndTemple dataset. `python -m nerf_sh.train --train_dir $CKPT_ROOT/$SCENE/ --config$CONFIG_FILE --data_dir $DATA_ROOT/$SCENE/` （NO Install GPU and TPU support for Jax.） There are the following errors ![bddb316a42cc6668d2bb1fed23a97f6](https://user-images.githubusercontent.com/27821863/118628434-2d54ae80-b7ff-11eb-908b-e03c9f93ea81.jpg) ![7633f460bbda3cd6f3040d11fae3c34](https://user-images.githubusercontent.com/27821863/118628449-304f9f00-b7ff-11eb-8547-47609b79f99f.jpg)

**Comment by zhywanna** [comment]
> When I Training and evaluation on TanksAndTemple dataset. `python -m nerf_sh.train --train_dir $CKPT_ROOT/$SCENE/ --config$CONFIG_FILE --data_dir $DATA_ROOT/$SCENE/` （NO Install GPU and TPU support for Jax.） There are the following errors ![bddb316a42cc6668d2bb1fed23a97f6](https://user-images.githubusercontent.com/27821863/118628434-2d54ae80-b7ff-11eb-908b-e03c9f93ea81.jpg) ![7633f460bbda3cd6f3040d11fae3c34](https://user-images.githubusercontent.com/27821863/118628449-304f9f00-b7ff-11eb-8547-47609b79f99f.jpg)

Have you ever solved this problem?
