### ISSUE TITLE
octree optimization does not work for LLFF dataset

### ISSUE THREAD

**Issue by Holmes-Alan** [sxyu/plenoctree#24]
Hello, I found that the codes seems not to work for LLFF dataset. I can successfully train the model for scene synthesis. However, when I try to use octree to extract the nerf model, it cannot work. i have tested that the codes work well for blender dataset. I wonder if the authors have any solutions. Thanks in advance.

**Comment by ENXING** [comment]
https://github.com/sxyu/plenoctree/issues/22
Could you share how to fix it?

**Comment by Holmes-Alan** [comment]
Could the authors please answer my question?

**Comment by Holmes-Alan** [comment]
I made a mistake. The code works. Thanks!
