### ISSUE TITLE
Did you  try directly optimize the octree, instead of after initialization with NeRF (or shNeRF) prediction?

### ISSUE THREAD

**Issue by rayleizhu** [sxyu/plenoctree#9]
How about directly training the otree without initialization?

**Comment by rayleizhu** [comment]
By the way, in the  readme, you mentioned that:

> For example, for the drums scene in the NeRF-Synthetic dataset, 100 / 10000 sampling view directions takes about 2 mins / 2 hours to finish the plenoctree extraction. It produce raw plenoctrees with PSNR=22.49 / 23.84 (before optimization). Note that extraction from a NeRF-SH model produce a raw plenoctree with PSNR=25.01.

How about after optimization? In another word, is the initialization important?

**Comment by longtermgoals** [comment]
Well, plenoxels it is.

**Comment by yangjiheng** [comment]
> By the way, in the readme, you mentioned that:
> 
> > For example, for the drums scene in the NeRF-Synthetic dataset, 100 / 10000 sampling view directions takes about 2 mins / 2 hours to finish the plenoctree extraction. It produce raw plenoctrees with PSNR=22.49 / 23.84 (before optimization). Note that extraction from a NeRF-SH model produce a raw plenoctree with PSNR=25.01.
> 
> How about after optimization? In another word, is the initialization important?

Well, seems like plenoxels you were talking about.

**Comment by rayleizhu** [comment]
> > By the way, in the readme, you mentioned that:
> > > For example, for the drums scene in the NeRF-Synthetic dataset, 100 / 10000 sampling view directions takes about 2 mins / 2 hours to finish the plenoctree extraction. It produce raw plenoctrees with PSNR=22.49 / 23.84 (before optimization). Note that extraction from a NeRF-SH model produce a raw plenoctree with PSNR=25.01.
> > 
> > 
> > How about after optimization? In another word, is the initialization important?
> 
> Well, seems like plenoxels you were talking about.

I know. It was Sep. 1st, 2021 when I raised the question. 

After I asked it here, I did some experiments to find the answer. I did figure out that the initialization is not important, and immediately realized that Alex Yu may already know this. Soon, Plenvoxels is published on Arxiv.
